06-wrappers
js-tasks-ru/vue-20230120_sergey-kirintsev pull request #6
Opened 2023-02-13 17:09 UTC by SergeyKirintsev

2023-02-13 17:10 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-14 19:13 UTC, ShGKme requested changes
В `06-wrappers/06-UiInputDate` при разработке обёртки компонента `UiInput` последний был "сломан". Он больше не работает для ввода текста.

2023-02-14 19:13 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    />
Здесь можно использовать динамический компонент, чтобы не дублировать всю реализацию. Например, при дублировании потерялся `@change` на `textarea`. Lazy на нём не сработает.

2023-02-14 19:13 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    />
Кстати, вметсо обработки обоих событий, можно динамически определять, какое событие обрабатывать: `@[eventName]="handler"`

2023-02-14 19:13 UTC, ShGKme commented on 06-wrappers/06-UiInputDate/components/UiInput.vue
> +      @[updateEvent]="$emit('update:modelValue', $event.target.valueAsNumber)"
Сейчас для разработки `<UiInputDate>` вы изменили реализацию компонента `<UiInput>`. Так в общем случае делать нельзя. Как минимум, это поменяло поведение `<UiInput>` во всех местах, где он используется. Теперь этот компонент сломался и не позволяет нигде вводить текстовые значение.

А в некоторых случаях у нас просто нет доступа к редактированию исходного кода оборачиваемых компонентов, если это компоненты из сторонних библиотек.

Вместо отправки здесь `valueAsNumber` можно в обёртке не привязывать `v-model` а обрабатывать событие `@input` и доставать `valueAsNumber` из события.

2023-02-24 04:59 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-24 15:33 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-02-24 15:34 UTC, merged